### ISSUE TITLE
rtsp live stream

### ISSUE THREAD

**Issue by mahamatnoumai** [mevo12318/face-recognition#1]
Hola amigo, este es muy interesante proyecto. 

gracias para compartir.

btw how can i stream using rstp camera?. gracias. another things. Gracias 

if you are planning to improve the project further later, you could add a function that won't let register a face already existed in the db or being registered. 

Gracias Hasta luego. Yo hablo poco espanol ✌🏾

**Comment by juan-csv** [comment]
Hi, to use a video streaming that comes through rstp I recommend that you read it with the opencv library like this:
```
cam = cv2.VideoCapture ("rtsp: // YOUR_STREAMING_IP_ADDRESS: PORT / foo.sdp")
ret, frame = cam.read ()
```

This method is responsible for acquiring your video frames ready to be processed, I recommend that you see this  [repo](https://github.com/juan-csv/face_recognition_occlusion) and add your RSTP url in the **main.py** file on **line 12** add your url so that you can start doing facial recognition in streaming, in this repo I also explain how to add new users.

Ten un buen día!!

**Comment by mahamatnoumai** [comment]
Gracias amigo.
